version: '3'

services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production

    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mydb
      - MONGO_INITDB_ROOT_PASSWORD=mypassword